chooseCRANmirror(graphics=FALSE, ind=31)
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

BiocManager::install("graph")
BiocManager::install("RBGL")
install.packages('ggm')
install.packages('pcalg')
install.packages('SID')
install.packages('glmnet')
install.packages('mboost')
install.packages('nlme')
install.packages('mgcv')
install.packages('CAM_1.0.tar.gz', repos = NULL, type="source")